---
- name: mbms login
  hosts: mbms
  gather_facts: false
  vars_prompt:
    - name: "command1"
      prompt: "What command would you like to run?"
      private: no

  tasks:
    - name: run with eric_eccli_command module, no register
      eric_eccli_command:
        commands:
          - "{{ command1 }}"

    - name: run with cli_command module, register supported
      cli_command:
        command: "{{ command1 }}"
      register: result

    - name: print registered result from cli_command module
      debug:
        msg: "{{result.stdout}}"
